export const REGISTRATION_SCREEN = 'REGISTRATION';
export const LOGIN_SCREEN = 'LOGIN';
export const ACTIVITY_SCREEN = 'ACTIVITY';
export const CHOOSE_ACTIVITY_SCREEN = 'CHOOSE_ACTIVITY';
export const CREATE_ACTIVITY_SCREEN = 'CREATE_ACTIVITY';
export const START_SCREEN = 'START';
